# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtransit.proto\x12\x04pyxy\"G\n\tSocketReq\x12\x10\n\x08socketId\x18\x01 \x01(\r\x12\n\n\x02ip\x18\x02 \x01(\r\x12\x0e\n\x06\x64omain\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\":\n\nSocketResp\x12\x10\n\x08socketId\x18\x01 \x01(\r\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\r\x12\x0c\n\x04port\x18\x03 \x01(\r\")\n\x07SendReq\x12\x10\n\x08socketId\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x1c\n\x08SendResp\x12\x10\n\x08socketId\x18\x01 \x01(\r\")\n\x07ReadReq\x12\x10\n\x08socketId\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x1c\n\x08ReadResp\x12\x10\n\x08response\x18\x01 \x01(\x0c\x32\xbf\x01\n\rSocketManager\x12*\n\x03new\x12\x0f.pyxy.SocketReq\x1a\x10.pyxy.SocketResp\"\x00\x12,\n\x05\x63lose\x12\x0f.pyxy.SocketReq\x1a\x10.pyxy.SocketResp\"\x00\x12)\n\x04send\x12\r.pyxy.SendReq\x1a\x0e.pyxy.SendResp\"\x00(\x01\x12)\n\x04read\x12\r.pyxy.ReadReq\x1a\x0e.pyxy.ReadResp\"\x00\x30\x01\x62\x06proto3')



_SOCKETREQ = DESCRIPTOR.message_types_by_name['SocketReq']
_SOCKETRESP = DESCRIPTOR.message_types_by_name['SocketResp']
_SENDREQ = DESCRIPTOR.message_types_by_name['SendReq']
_SENDRESP = DESCRIPTOR.message_types_by_name['SendResp']
_READREQ = DESCRIPTOR.message_types_by_name['ReadReq']
_READRESP = DESCRIPTOR.message_types_by_name['ReadResp']
SocketReq = _reflection.GeneratedProtocolMessageType('SocketReq', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETREQ,
  '__module__' : 'transit_pb2'
  # @@protoc_insertion_point(class_scope:pyxy.SocketReq)
  })
_sym_db.RegisterMessage(SocketReq)

SocketResp = _reflection.GeneratedProtocolMessageType('SocketResp', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETRESP,
  '__module__' : 'transit_pb2'
  # @@protoc_insertion_point(class_scope:pyxy.SocketResp)
  })
_sym_db.RegisterMessage(SocketResp)

SendReq = _reflection.GeneratedProtocolMessageType('SendReq', (_message.Message,), {
  'DESCRIPTOR' : _SENDREQ,
  '__module__' : 'transit_pb2'
  # @@protoc_insertion_point(class_scope:pyxy.SendReq)
  })
_sym_db.RegisterMessage(SendReq)

SendResp = _reflection.GeneratedProtocolMessageType('SendResp', (_message.Message,), {
  'DESCRIPTOR' : _SENDRESP,
  '__module__' : 'transit_pb2'
  # @@protoc_insertion_point(class_scope:pyxy.SendResp)
  })
_sym_db.RegisterMessage(SendResp)

ReadReq = _reflection.GeneratedProtocolMessageType('ReadReq', (_message.Message,), {
  'DESCRIPTOR' : _READREQ,
  '__module__' : 'transit_pb2'
  # @@protoc_insertion_point(class_scope:pyxy.ReadReq)
  })
_sym_db.RegisterMessage(ReadReq)

ReadResp = _reflection.GeneratedProtocolMessageType('ReadResp', (_message.Message,), {
  'DESCRIPTOR' : _READRESP,
  '__module__' : 'transit_pb2'
  # @@protoc_insertion_point(class_scope:pyxy.ReadResp)
  })
_sym_db.RegisterMessage(ReadResp)

_SOCKETMANAGER = DESCRIPTOR.services_by_name['SocketManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOCKETREQ._serialized_start=23
  _SOCKETREQ._serialized_end=94
  _SOCKETRESP._serialized_start=96
  _SOCKETRESP._serialized_end=154
  _SENDREQ._serialized_start=156
  _SENDREQ._serialized_end=197
  _SENDRESP._serialized_start=199
  _SENDRESP._serialized_end=227
  _READREQ._serialized_start=229
  _READREQ._serialized_end=270
  _READRESP._serialized_start=272
  _READRESP._serialized_end=300
  _SOCKETMANAGER._serialized_start=303
  _SOCKETMANAGER._serialized_end=494
# @@protoc_insertion_point(module_scope)
